#!/usr/bin/env python3
"""Tests for the parts of capture and restore that don't need iTerm running.

A live restore opens a dozen windows on top of whatever you're doing, so it is
not something CI (or a working machine) can run. These cover the logic that
would otherwise only be exercised by that untestable path: shell quoting,
mission extraction, stale-tag rejection, session-id inference, and the
window/tab structure the driver plans from a capture.

    python3 tests/test_snapshot_restore.py
"""

import importlib.util
import json
import os
import sys
import tempfile
import unittest
from datetime import datetime, timedelta

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load(name, path):
    spec = importlib.util.spec_from_file_location(name, os.path.join(REPO, path))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


# The driver reads sys.argv at import time; keep it out of restore mode.
_argv = sys.argv
sys.argv = ["claude-restore-driver.py", "--dry-run"]
driver = load("driver", "scripts/claude-restore-driver.py")
sys.argv = _argv

snapshot = load("snapshot", "scripts/claude-iterm-snapshot.py")


class ShellQuoting(unittest.TestCase):
    """A session named "Blocking Dana's iPhone hotspot" used to break the
    command line it was interpolated into, leaving the shell mid-quote."""

    def cmd(self, **over):
        sdef = {
            "name": "plain",
            "badge": "plain",
            "cwd": "/tmp/work",
            "claude_session_id": "abc-123",
        }
        sdef.update(over)
        return driver.build_cmd(sdef)

    def test_apostrophe_in_name_does_not_break_quoting(self):
        cmd = self.cmd(name="Blocking Dana's iPhone hotspot")
        self.assertNotIn("'Blocking Dana's", cmd)
        self.assertIn("iPhone hotspot", cmd)

    def test_apostrophe_in_badge_does_not_break_quoting(self):
        self.assertIn("base64", self.cmd(badge="Dana's"))

    def test_metacharacters_are_not_executed(self):
        for hostile in ("; rm -rf /tmp/x", "$(id)", "`id`", "a && b"):
            cmd = self.cmd(name=hostile)
            self.assertNotIn(f"; {hostile}", cmd)
            self.assertIn("claude --resume", cmd)

    def test_cwd_with_spaces_is_quoted(self):
        self.assertIn("'/tmp/my work'", self.cmd(cwd="/tmp/my work"))

    def test_resume_only_when_an_id_is_present(self):
        self.assertIn("claude --resume abc-123", self.cmd())
        self.assertTrue(self.cmd(claude_session_id=None).endswith("&& claude"))


class MissionText(unittest.TestCase):
    """The mission should read as the human's own words, not Claude Code's
    injected bookkeeping."""

    def test_wrapper_records_are_rejected(self):
        for wrapper in (
            "<local-command-caveat>Caveat: the messages below…</local-command-caveat>",
            "<command-name>/model</command-name>",
            "<system-reminder>be brief</system-reminder>",
            "Caveat: The messages below were generated by the user",
            "This session is being continued from a previous conversation",
        ):
            self.assertIsNone(snapshot._clean_mission(wrapper))

    def test_pasted_content_is_stripped_but_the_ask_survives(self):
        cleaned = snapshot._clean_mission(
            "Fix the login bug <pasted_content id='x'>500 lines</pasted_content> today"
        )
        self.assertNotIn("500 lines", cleaned)
        self.assertIn("Fix the login bug", cleaned)
        self.assertIn("today", cleaned)

    def test_newlines_collapse_to_one_line(self):
        self.assertEqual(snapshot._clean_mission("a\n\n  b\tc"), "a b c")

    def test_empty_after_cleaning_is_none(self):
        self.assertIsNone(snapshot._clean_mission("   <tag></tag>  "))


class SlugMapping(unittest.TestCase):
    def test_path_becomes_project_dir_name(self):
        self.assertEqual(
            snapshot.slug_for_cwd("/srv/Sites/politogy"), "-srv-Sites-politogy"
        )

    def test_dots_are_replaced_too(self):
        self.assertEqual(snapshot.slug_for_cwd("/a/b.c"), "-a-b-c")


class SessionIdInference(unittest.TestCase):
    """Sessions that predate the tagging hook are matched by comparing the
    `claude` process start time to each transcript's first timestamp."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.cwd = "/srv/Sites"
        self.slug = snapshot.slug_for_cwd(self.cwd)
        os.makedirs(os.path.join(self.tmp.name, self.slug))
        self._orig = snapshot.PROJECTS_DIR
        snapshot.PROJECTS_DIR = self.tmp.name
        self.addCleanup(lambda: setattr(snapshot, "PROJECTS_DIR", self._orig))
        snapshot._slug_first_ts.clear()
        snapshot._claimed_ids.clear()
        snapshot._live_procs = None

    def write_transcript(self, sid, when):
        path = os.path.join(self.tmp.name, self.slug, f"{sid}.jsonl")
        with open(path, "w") as fh:
            fh.write(json.dumps({"type": "summary", "summary": "no timestamp"}) + "\n")
            fh.write(json.dumps({"type": "user", "timestamp": when.isoformat()}) + "\n")
        return path

    def set_procs(self, procs):
        snapshot._live_procs = procs

    def test_nearest_transcript_after_process_start_wins(self):
        start = datetime(2026, 9, 21, 12, 0, 0)
        self.write_transcript("early", start - timedelta(hours=3))
        self.write_transcript("match", start + timedelta(seconds=2))
        self.write_transcript("later", start + timedelta(hours=1))
        self.set_procs([("1", "ttys9", start.timestamp())])
        self.assertEqual(snapshot.infer_session_id("/dev/ttys9", self.cwd), "match")

    def test_two_sessions_in_one_directory_do_not_collide(self):
        a = datetime(2026, 9, 21, 9, 0, 0)
        b = datetime(2026, 9, 21, 11, 30, 0)
        self.write_transcript("sid-a", a + timedelta(seconds=1))
        self.write_transcript("sid-b", b + timedelta(seconds=1))
        self.set_procs([("1", "ttys1", a.timestamp()), ("2", "ttys2", b.timestamp())])
        self.assertEqual(snapshot.infer_session_id("/dev/ttys1", self.cwd), "sid-a")
        self.assertEqual(snapshot.infer_session_id("/dev/ttys2", self.cwd), "sid-b")

    def test_an_id_is_never_handed_out_twice(self):
        start = datetime(2026, 9, 21, 12, 0, 0)
        self.write_transcript("only", start + timedelta(seconds=1))
        self.set_procs([
            ("1", "ttys1", start.timestamp()),
            ("2", "ttys2", start.timestamp()),
        ])
        self.assertEqual(snapshot.infer_session_id("/dev/ttys1", self.cwd), "only")
        self.assertIsNone(snapshot.infer_session_id("/dev/ttys2", self.cwd))

    def test_transcript_long_before_the_process_is_not_a_match(self):
        start = datetime(2026, 9, 21, 12, 0, 0)
        self.write_transcript("stale", start - timedelta(days=2))
        self.set_procs([("1", "ttys9", start.timestamp())])
        self.assertIsNone(snapshot.infer_session_id("/dev/ttys9", self.cwd))

    def test_no_live_process_on_that_tty(self):
        self.set_procs([])
        self.assertIsNone(snapshot.infer_session_id("/dev/ttys9", self.cwd))

    def test_stale_tag_is_detected_by_its_missing_transcript(self):
        self.write_transcript("real", datetime(2026, 9, 21, 12, 0, 0))
        self.assertTrue(snapshot.transcript_exists("real", self.cwd))
        self.assertFalse(snapshot.transcript_exists("left-behind", self.cwd))


class PlannedStructure(unittest.TestCase):
    """Restore must rebuild what was captured, not regroup it by project."""

    CAPTURE = {
        "windows": [
            {
                "window_id": 1,
                "title": "One",
                "frame": {"x": 0, "y": 0, "w": 100, "h": 100},
                "space": 3,
                "tabs": [
                    {"index": 1, "title": "t1", "sessions": [
                        {"name": "a", "badge": "", "cwd": "/p/alpha",
                         "claude_session_id": "id-a", "mission": "do a"}]},
                    {"index": 2, "title": "t2", "sessions": [
                        {"name": "b", "badge": "", "cwd": "/p/beta",
                         "claude_session_id": "id-b", "mission": None}]},
                ],
            },
            {
                "window_id": 2,
                "title": "Two",
                "frame": {"x": 5, "y": 5, "w": 50, "h": 50},
                "space": -1,
                "tabs": [
                    {"index": 1, "title": "t1", "sessions": [
                        {"name": "c", "badge": "", "cwd": "/p/alpha",
                         "claude_session_id": None, "mission": None}]},
                ],
            },
        ]
    }

    def plan(self):
        return driver.build_plan(self.CAPTURE["windows"])

    def test_window_and_tab_counts_match_the_capture(self):
        lines = self.plan()
        self.assertEqual(sum(l.startswith("[window ") for l in lines), 2)
        self.assertEqual(sum(l.strip().startswith("[tab ") for l in lines), 3)

    def test_two_directories_in_one_window_are_not_split_apart(self):
        lines = self.plan()
        second = next(i for i, l in enumerate(lines) if l.startswith("[window 2]"))
        first_window = "\n".join(lines[:second])
        self.assertIn("/p/alpha", first_window)
        self.assertIn("/p/beta", first_window)

    def test_tabs_keep_their_captured_order(self):
        order = [l for l in self.plan() if l.strip().startswith("[tab ")]
        self.assertEqual(order[0].strip(), "[tab 1] title='t1'")
        self.assertEqual(order[1].strip(), "[tab 2] title='t2'")

    def test_known_space_is_applied_and_unknown_is_skipped(self):
        plan = "\n".join(self.plan())
        self.assertIn("spacesctl move <new-window-id> 3", plan)
        self.assertIn("space unknown", plan)

    def test_a_session_without_an_id_starts_fresh(self):
        plan = "\n".join(self.plan())
        self.assertIn("cmd='claude --resume id-a'", plan)
        self.assertIn("cmd='claude'", plan)


class MissionReminder(unittest.TestCase):
    def test_reminder_quotes_the_mission(self):
        self.assertIn("do the thing", driver.mission_reminder("do the thing"))

    def test_no_mission_means_no_reminder(self):
        self.assertFalse((driver.mission_reminder(None) or "").strip())



class TranscriptLookupAcrossProjects(unittest.TestCase):
    """A session launched above its working directory keeps its transcript in
    the launch directory's project folder. Looking only where the pane sits
    now threw away a valid tag and lost the session."""

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self._orig = snapshot.PROJECTS_DIR
        snapshot.PROJECTS_DIR = self.tmp.name
        self.addCleanup(lambda: setattr(snapshot, "PROJECTS_DIR", self._orig))
        self.launched_in = "/srv/Sites"
        self.now_in = "/srv/Sites/one-project"
        d = os.path.join(self.tmp.name, snapshot.slug_for_cwd(self.launched_in))
        os.makedirs(d)
        with open(os.path.join(d, "sid-1.jsonl"), "w") as fh:
            fh.write(json.dumps({"type": "mode", "sessionId": "sid-1"}) + "\n")
            fh.write(json.dumps({"type": "user", "cwd": self.launched_in,
                                 "timestamp": "2026-09-21T12:00:00Z"}) + "\n")
            fh.write(json.dumps({"type": "user", "cwd": self.now_in,
                                 "timestamp": "2026-09-21T12:30:00Z"}) + "\n")

    def test_found_from_a_subdirectory(self):
        self.assertIsNotNone(snapshot.find_transcript("sid-1", self.now_in))

    def test_a_valid_tag_is_not_treated_as_stale(self):
        self.assertTrue(snapshot.transcript_exists("sid-1", self.now_in))

    def test_a_genuinely_missing_transcript_still_reads_as_stale(self):
        self.assertFalse(snapshot.transcript_exists("gone", self.now_in))

    def test_resume_dir_is_where_claude_was_launched(self):
        self.assertEqual(
            snapshot.resume_cwd_for("sid-1", self.now_in), self.launched_in
        )

    def test_unknown_session_falls_back_to_the_pane_cwd(self):
        self.assertEqual(snapshot.resume_cwd_for("gone", self.now_in), self.now_in)


class ResumeDirectory(unittest.TestCase):
    def test_restore_cds_to_the_launch_dir_not_the_pane_cwd(self):
        cmd = driver.build_cmd({
            "name": "x", "badge": "", "cwd": "/srv/Sites/one-project",
            "resume_cwd": "/srv/Sites", "claude_session_id": "sid-1",
        })
        self.assertIn("cd /srv/Sites &&", cmd)

    def test_a_fresh_session_still_opens_in_its_own_cwd(self):
        cmd = driver.build_cmd({
            "name": "x", "badge": "", "cwd": "/srv/Sites/one-project",
            "resume_cwd": "/srv/Sites", "claude_session_id": None,
        })
        self.assertIn("cd /srv/Sites/one-project &&", cmd)

    def test_captures_without_resume_cwd_still_work(self):
        cmd = driver.build_cmd({
            "name": "x", "badge": "", "cwd": "/srv/Sites/one-project",
            "claude_session_id": "sid-1",
        })
        self.assertIn("cd /srv/Sites/one-project &&", cmd)



if __name__ == "__main__":
    unittest.main(verbosity=2)
